FROM node:18-alpine AS builder
RUN apk add --no-cache python3 make g++

WORKDIR /app

# зависимости
RUN --mount=type=bind,source=package.json,target=package.json \
  --mount=type=bind,source=package-lock.json,target=package-lock.json \
  npm ci

CMD ["sh", "-c", "npx prisma generate && npx prisma migrate dev && npm run start:dev"]

