services:
  app-dev:
    container_name: svc-users-app-dev
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - ./src:/app/src:ro
      - ./prisma:/app/prisma:ro
      - ./test:/app/test:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./tsconfig.build.json:/app/tsconfig.build.json:ro
      - ./eslint.config.mjs:/app/eslint.config.mjs:ro
      - ./jest.config.js:/app/jest.config.js:ro
      - ./.env:/app/.env:ro
      - ./package.json:/app/package.json:ro
    depends_on:
      - postgres
    cap_add:
      - NET_BIND_SERVICE
    environment:
      PORT: 80

    networks:
      net:
        ipv6_address: fd98:2dd6:8f48:1d99:dc28:e6e1::2

  postgres:
    image: postgres:18-alpine
    container_name: svc-users-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb

    networks:
      net:
        ipv6_address: fd98:2dd6:8f48:1d99:dc28:e6e1::3

    volumes:
      - db:/var/lib/postgresql/data

networks:
  net:
    enable_ipv6: true
    enable_ipv4: false
    driver_opts:
      com.docker.network.driver.mtu: "65535"
    ipam:
      config:
        - subnet: fd98:2dd6:8f48:1d99:dc28:e6e1::/96
  host_bridge:
    external: true
    name: bridge

volumes:
  db:
