services:
  postgres:
    image: postgres:18-alpine
    container_name: svc-users-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb

    networks:
      shared-net:
        ipv6_address: fd98:2dd6:8f48:1d99:dc28:e6e1::3

    volumes:
      - db:/var/lib/postgresql

networks:
  shared-net:
    external: true
    name: svc-net

volumes:
  db:
