FROM node:lts-alpine3.23 AS builder

WORKDIR /app

# зависимости
RUN --mount=type=bind,source=package.json,target=package.json \
  --mount=type=bind,source=package-lock.json,target=package-lock.json \
  npm ci

CMD ["sh", "-c", "npx prisma generate && npx prisma migrate dev && npm run start:dev"]

