services:
  postgres:
    image: postgres:18-alpine
    container_name: svc-users-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    networks:
      net:
        ipv6_address: fd98:2dd6:8f48:1d99:dc28:e6e1::3
    volumes:
      - db:/var/lib/postgresql/data

networks:
  net:
    enable_ipv6: true
    enable_ipv4: false
    driver_opts:
      com.docker.network.driver.mtu: "65535"
    ipam:
      config:
        - subnet: fd98:2dd6:8f48:1d99:dc28:e6e1::/96

volumes:
  db: