export enum UserCodes {
  USER_CREATED = 'USER_CREATED',
  USER_FETCHED_OK = 'USER_FETCHED_OK',
  USER_LIST_FETCHED = 'USER_LIST_FETCHED',
  USER_DELETED = 'USER_DELETED',
  ROLES_UPDATED = 'ROLES_UPDATED',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_INVALID_DATA = 'USER_INVALID_DATA',
  USER_DUPLICATE = 'USER_DUPLICATE',
  USER_INTERNAL_ERROR = 'USER_INTERNAL_ERROR',
}
