export const GroupCodes = {
  GROUP_CREATED: 'GROUP_CREATED',
  GROUP_FETCHED: 'GROUP_FETCHED',
  GROUP_LIST_FETCHED: 'GROUP_LIST_FETCHED',
  GROUP_UPDATED: 'GROUP_UPDATED',
  GROUP_DELETED: 'GROUP_DELETED',

  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  GROUP_INVALID_DATA: 'GROUP_INVALID_DATA',
  GROUP_ALREADY_EXISTS: 'GROUP_ALREADY_EXISTS',
  GROUP_INTERNAL_ERROR: 'GROUP_INTERNAL_ERROR',

  GROUP_PERMISSION_ADDED: 'GROUP_PERMISSION_ADDED',
  GROUP_PERMISSION_REMOVED: 'GROUP_PERMISSION_REMOVED',
  GROUP_PERMISSION_EXISTS: 'GROUP_PERMISSION_EXISTS',
  GROUP_PERMISSION_NOT_FOUND: 'GROUP_PERMISSION_NOT_FOUND',

  GROUP_USER_IN_GROUP: 'GROUP_USER_IN_GROUP',
  GROUP_USER_NOT_IN_GROUP: 'GROUP_USER_NOT_IN_GROUP',

  GROUP_PERMISSIONS_UPDATED: 'GROUP_PERMISSIONS_UPDATED',

  GROUP_CHECK: 'GROUP_CHECK',
} as const;
