app:
  name: svc-users
  env: dev
  port: 9002

log:
  level: debug

postgres:
  host: postgres
  port: 5432
  user: usersvc
  password: usersvc
  dbname: usersvc
  sslmode: disable

prometheus:
  enabled: true
  path: /metrics

